name: Generate Test Cases

on:
  workflow_dispatch:
    inputs:
      requirement:
        description: 'Requirement Description'
        required: true
      squad:
        description: 'Squad Name'
        required: true
      filename:
        description: 'Test Case File Name (without extension)'
        required: false
      no_upload:
        description: 'Skip GitHub upload?'
        required: false
        default: 'false'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -e .

      - name: Generate Test Cases
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO_OWNER: ${{ github.repository_owner }}
          GITHUB_REPO_NAME: ${{ github.event.repository.name }}
          GITHUB_BRANCH: main
          REQUIREMENT: ${{ github.event.inputs.requirement }}
          SQUAD: ${{ github.event.inputs.squad }}
          FILENAME: ${{ github.event.inputs.filename }}
          NO_UPLOAD: ${{ github.event.inputs.no_upload }}
        run: |
          generate-tests
