name: Generate Test Cases

on:
  workflow_dispatch:
    inputs:
      requirement:
        description: "Requirement description"
        required: true
      tribe:
        description: "Tribe name (select the correct tribe)"
        required: true
        type: choice
        options:
          - select
          - Shopping
          - Growth
          - Q-Commerce
          - Fintech
          - Lifecycle
      squad:
        description: "Squad name (select the correct squad)"
        required: true
        type: choice
        options:
          - select
          - Home
          - User & Location
          - Food-Discovery
          - Food-Finding
          - Menu experience
          - Cart and checkout
          - Tracking & User Support
          - Pro
          - Incentives Experience
          - Incentive core
          - Adex
          - QC affordability
          - QC Finding And browsing
          - Grocery Ordering
          - Grocery Fulfillment
          - Dineout
          - Pay Acceptance
          - tPay
          - Postpaid
      background:
        description: "Primary background context (e.g., Talabat food mobile application)"
        required: true
        default: "Talabat food mobile application"
      additional-background:
        description: "Additional context (e.g., logged in user, pro subscribed user)"
        required: false
      file-name:
        description: "Test file name (e.g., login-with-email)"
        required: true
      tag:
        description: "Priority tag (e.g., P0, P1)"
        required: true
      other-tags:
        description: "Other tags (e.g., smoke, login, regression)"
        required: false

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Validate input fields
        run: |
          if [ "${{ github.event.inputs.tribe }}" = "select" ]; then
            echo "❌ Tribe name is not selected. Please choose a valid tribe."
            exit 1
          fi
          if [ "${{ github.event.inputs.squad }}" = "select" ]; then
            echo "❌ Squad name is not selected. Please choose a valid squad."
            exit 1
          fi

      - name: Generate test cases
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO_OWNER: ${{ github.repository_owner }}
          GITHUB_REPO_NAME: ${{ github.event.repository.name }}
          GITHUB_BRANCH: ${{ github.ref_name }}
        run: |
          generate-tests \
            --requirement "${{ github.event.inputs.requirement }}" \
            --tribe "${{ github.event.inputs.tribe }}" \
            --squad "${{ github.event.inputs.squad }}" \
            --file-name "${{ github.event.inputs.file-name }}" \
            --tag "${{ github.event.inputs.tag }}" \
            --other-tags "${{ github.event.inputs.other-tags }}" \
            --background "${{ github.event.inputs.background }}" \
            --additional-background "${{ github.event.inputs.additional-background }}"
