name: Generate Test Cases

on:
  workflow_dispatch:
    inputs:
      requirement:
        description: "Requirement description"
        required: true
      squad:
        description: "Squad name (e.g., squad-auth)"
        required: true
      file-name:
        description: "Test file name (e.g., login-with-email)"
        required: false
      tag:
        description: "Priority tag (e.g., P0, P1)"
        required: false
      other-tags:
        description: "Other tags (e.g., smoke, login, regression)"
        required: false
      background:
        description: "Context or shared background (e.g., user is logged in, food items in cart)"
        required: false
      pre-requisite:
        description: "Pre-requisites or setup steps before test scenarios (e.g., user account exists)"
        required: false

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Generate test cases
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO_OWNER: ${{ github.repository_owner }}
          GITHUB_REPO_NAME: ${{ github.event.repository.name }}
          GITHUB_BRANCH: ${{ github.ref_name }}
        run: |
          generate-tests \
            --requirement "${{ github.event.inputs.requirement }}" \
            --squad "${{ github.event.inputs.squad }}" \
            --file-name "${{ github.event.inputs.file-name }}" \
            --tag "${{ github.event.inputs.tag }}" \
            --other-tags "${{ github.event.inputs.other-tags }}" \
            --background "${{ github.event.inputs.background }}" \
            --pre-requisite "${{ github.event.inputs.pre-requisite }}"
